
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiisixdctrokfmhnrxnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpaXNpeGRjdHJva2ZtaG5yeG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODU2NDEsImV4cCI6MjA2MDA2MTY0MX0.hB5TQplwny_IJDs2r3R9K33m3zxfmKGSSi1uXGnN3bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  }
});
